### ISSUE TITLE
urllib2.URLError

### ISSUE THREAD

**Issue by asifiqbal** [justgrimes/WMATA-SmarTrip-Scraper#2]
I am getting EOF occurred in violation of protocol

From the browser I can login fine with my account and can check my
smarttrip usage history upto 31 days.

$ python WMATAscraper.py 
Traceback (most recent call last):
  File "WMATAscraper.py", line 11, in <module>
    br.open("https://smartrip.wmata.com/Account/AccountLogin.aspx") #login page
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 230, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 344, in _open
    '_open', req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 332, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1170, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1118, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

**Comment by klapauciuz** [comment]
are you fixed this?
